name: Run tests

"on":
  push:
    branches: [master, main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          lfs: false
          submodules: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Run Tests
        run: |
          make build install_local_raw test
